export const DO_LOADING_LOGIN ='DO_LOADING_LOGIN';
export const LOGIN_USER ='LOGIN_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REDIRECT = "REDIRECT";

export const REGISTERED ="REGISTERED";
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const DO_REGISTER = 'DO_REGISTER';
export const PROFILE_LOAD_SUCCESSFULLY = 'PROFILE_LOAD_SUCCESSFULLY';
export const PROFILE_LOAD_FAILED = 'PROFILE_LOAD_FAILED';

export const ADD_RIDE_SUCCESSFULL = "ADD_RIDE_SUCCESSFULL";
export const ADD_RIDE_UNSUCCESSFULL = "ADD_RIDE_UNSUCCESSFULL";
export const DOING_ADD_RIDE = "DOING_ADD_RIDE";

export const SEARCH_BOOK_RIDE = "SEARCH_BOOK_RIDE";
export const BOOKED_RIDE = "BOOKED_RIDE";
export const BOOK_RIDE_FAILED = "BOOK_RIDE_FAILED";

export const RIDE_HISTORY_ADDED = 'RIDE_HISTORY_ADDED';
export const RIDE_HISTORY_ADDED_FAILED = "RIDE_HISTORY_ADDED_FAILED";