export const DO_LOADING_LOGIN ='DO_LOADING_LOGIN';
export const LOGIN_USER ='LOGIN_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REDIRECT = "REDIRECT";

export const REGISTERED ="REGISTERED";
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const DO_REGISTER = 'DO_REGISTER';
export const PROFILE_LOAD_SUCCESSFULLY = 'PROFILE_LOAD_SUCCESSFULLY';
export const PROFILE_LOAD_FAILED = 'PROFILE_LOAD_FAILED';